version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.1.3-cli-jessie
        steps:
            - checkout
            - restore_cache:
                keys:
                    # No targeted cache as libraries contain no Composer lock file
                    - deps-v1-
            - run:
                name: Install dependencies
                command: composer install --no-interaction --no-progress
            - save_cache:
                key: deps-v1-
                paths:
                    - vendor
            - run:
                name: Run unit tests
                command: vendor/bin/phpunit
