version: 2
jobs:
    test:
        docker:
            - image: circleci/php:7.2.0-cli-stretch
        steps:
            - checkout
            - restore_cache:
                keys:
                    # No targeted cache as libraries contain no Composer lock file
                    - deps-v1-
            - run: composer install --no-interaction --no-progress
            - save_cache:
                key: deps-v1-
                paths:
                    - vendor
            - run: vendor/bin/phpunit
